nome = input('Qual é o seu nome? ')
data = input('Dia do nascimento: ')
mes = input('Mes do seu nascimento: ')
ano = input('Ano do seu nascimento: ')
num1 = input('Primeiro número: ')
num2 = input('Segundo número: ')
soma = int(num1) + int(num2)
print(f'Olá {nome}! Prazer em te conhecer!!!')
print(f'O senhor nasceu {data}/{mes}/{ano}')
print(soma)